---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/register":
    post:
      summary: register user
      tags:
      - Auth
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - name
                  - email
                  - password
                  - password_confirmation
  "/login":
    post:
      summary: login user
      tags:
      - Auth
      parameters:
      - name: email
        in: query
        required: true
        schema:
          type: string
      - name: password
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
  "/thread_posts/{thread_post_id}/comments":
    parameters:
    - name: thread_post_id
      in: path
      description: ThreadPost ID
      required: true
      schema:
        type: string
    get:
      summary: list comments
      tags:
      - Comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comments
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                content:
                  type: string
                parent_id:
                  type: integer
                  nullable: true
              required:
              - user_id
              - content
  "/thread_posts/{thread_post_id}/comments/{id}":
    parameters:
    - name: thread_post_id
      in: path
      description: ThreadPost ID
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: Comment ID
      required: true
      schema:
        type: string
    delete:
      summary: delete comment
      tags:
      - Comments
      security:
      - bearerAuth: []
      responses:
        '204':
          description: no content
  "/home":
    get:
      summary: List all thread posts
      tags:
      - Home
      parameters:
      - name: page
        in: query
        required: false
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      responses:
        '200':
          description: thread posts retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  thread_posts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        content:
                          type: string
                        user_id:
                          type: integer
                        created_at:
                          type: string
                          format: date-time
                        updated_at:
                          type: string
                          format: date-time
                        comments_count:
                          type: integer
                        user:
                          type: object
                          properties:
                            id:
                              type: integer
                            name:
                              type: string
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
                  total_count:
                    type: integer
  "/thread_posts":
    get:
      summary: list thread_posts
      tags:
      - ThreadPosts
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    post:
      summary: create thread_post
      tags:
      - ThreadPosts
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
              - title
              - content
  "/thread_posts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show thread_post
      tags:
      - ThreadPosts
      responses:
        '200':
          description: successful
    put:
      summary: update thread_post
      tags:
      - ThreadPosts
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
        '403':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
              required:
              - title
              - content
    delete:
      summary: delete thread_post
      tags:
      - ThreadPosts
      security:
      - bearerAuth: []
      responses:
        '204':
          description: no content
        '401':
          description: unauthorized
        '403':
          description: forbidden
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
